services:
  aworld:
    build:
      context: .
    container_name: aworld
    network_mode: host
    environment:
      IN_DOCKER: "1"
      PYTHONUNBUFFERED: "1"
      DISPLAY: ${DISPLAY}
    working_dir: /workspace
    command: ["bash", "scripts/run.sh"]
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./src:/workspace/src
      - ./scripts:/workspace/scripts
