HEARTBEAT_TIMEOUT_S = 3.0
TELEMETRY_TIMEOUT_S = 0.001
GLOBAL_POSITION_INT_INTERVAL_US = 200_000

GUIDED_RETRY_S = 3.0
GUIDED_TIMEOUT_S = 10.0
GUIDED_MODE = "GUIDED_NOGPS"
ARM_RETRY_S = 3.0
ARM_TIMEOUT_S = 90.0

MISSION_ALT_REACH_UP_M = 15.0
MISSION_HOLD_S = 20.0
MISSION_ALT_DESCEND_M = 10.0
ALTITUDE_TOLERANCE_M = 0.3

LAND_COMPLETE_ALT_M = 0
LAND_RETRY_S = 1.0
LAND_TIMEOUT_S = 10.0

# Thrust altitude controller params (cascaded altitude->velocity->accel)
THRUST_SEND_HZ = 10.0

ALT_KP = 0.2

VEL_KP = 1.0
VEL_KI = 1.0

VEL_INTEGRAL_MIN = -1.0
VEL_INTEGRAL_MAX = 1.0

MAX_UP_SPEED_MPS = 1.0
MAX_DOWN_SPEED_MPS = 1.0

MAX_UP_ACCEL_MPS2 = 0.4
MAX_DOWN_ACCEL_MPS2 = 0.4

HOVER_THRUST = 0.39
MIN_THRUST = 0.1
MAX_THRUST = 0.9